[package]
name = "rsspls"
version = "0.4.0"
edition = "2021"
authors = [
    "Wesley Moore <wes@wezm.net>"
]

homepage = "https://github.com/wezm/rsspls"
repository = "https://github.com/wezm/rsspls.git"

readme = "README.md"
license = "MIT OR Apache-2.0"

description = "Generate RSS feeds from websites"
keywords = ["rss", "cli", "html", "webpage", "feed"]
categories = ["command-line-utilities", "web-programming"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anydate = "0.3.0"
atomicwrites = "0.3.1"
chrono = { version = "0.4.23", default-features = false }
futures = { version = "0.3.25", default-features = false, features = ["std"] }
kuchiki = "0.8.1"
log = "0.4.17"
pico-args = "0.5.0"
pretty_env_logger = "0.4.0"
reqwest = { version = "0.11.13", default-features = false, features = ["rustls-tls", "gzip"] }
rss = "2.0.2"
serde = { version = "1.0.152", features = ["derive"] }
simple-eyre = "0.3.1"
tokio = { version = "1.24.2", features = ["rt-multi-thread", "macros"] }
toml = "0.5.10"
url = "2.3.1"

[dependencies.time]
#version = "0.3.17"
git = "https://github.com/time-rs/time.git"
rev = "43862d294546177a331038ff49adf80d87507622"
features = ["parsing", "formatting", "macros"]

[target.'cfg(windows)'.dependencies]
dirs = "4.0.0"

[target.'cfg(not(windows))'.dependencies]
xdg = "2.4.1"
