[package]
name = "rsspls"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "3.2.8", features = ["derive"] }
kuchiki = "0.8.1"
log = "0.4.17"
pretty_env_logger = "0.4.0"
reqwest = { version = "0.11.11", default-features = false, features = ["rustls-tls", "gzip"] }
rss = "2.0.1"
serde = { version = "1.0.137", features = ["derive"] }
simple-eyre = "0.3.1"
tokio = { version = "1.19.2", features = ["full"] }
toml = "0.5.9"
